============================= test session starts ==============================
platform darwin -- Python 3.9.13, pytest-7.1.2, pluggy-1.0.0 -- /Users/nicolasbancel/.pyenv/versions/myenv-metabase-questions/bin/python
cachedir: .pytest_cache
rootdir: /Users/nicolasbancel/git/lewagon/data-engineering-solutions/01-Data-Storage-and-Batch-Pipelines/02-SQL/03-SQL-Advanced
collecting ... collected 9 items

tests/test_exercice_1_1.py::test_correct_columns PASSED                  [ 11%]
tests/test_exercice_1_1.py::test_correct_filters PASSED                  [ 22%]
tests/test_exercice_1_2.py::test_correct_filters PASSED                  [ 33%]
tests/test_exercice_1_2.py::test_correct_metric_calculation FAILED       [ 44%]
tests/test_exercice_2.py::test_correct_columns_and_size PASSED           [ 55%]
tests/test_exercice_2.py::test_correct_metric_calculation PASSED         [ 66%]
tests/test_exercice_3.py::test_correct_columns_and_size PASSED           [ 77%]
tests/test_exercice_4.py::test_correct_columns_and_size PASSED           [ 88%]
tests/test_exercice_4.py::test_ctest_correct_metric_calculation PASSED   [100%]

=================================== FAILURES ===================================
_______________________ test_correct_metric_calculation ________________________

    def test_correct_metric_calculation():
        bambi_profit_absolute = df_1_2[df_1_2["id"] == 3170].reset_index()["profit_absolute"][0]
        assert bambi_profit_absolute == 266589150.0, "Profit absolute calculation incorrect"
    
        bambi_profit_percentage = df_1_2[df_1_2["id"] == 3170].reset_index()["profit_percentage"][0]
>       assert bambi_profit_percentage == 310.71, "Profit percentage calculation incorrect - did you round up to 2 decimals ?"
E       AssertionError: Profit percentage calculation incorrect - did you round up to 2 decimals ?
E       assert 1.0 == 310.71

tests/test_exercice_1_2.py:31: AssertionError
=============================== warnings summary ===============================
../../../../../../.pyenv/versions/myenv-metabase-questions/lib/python3.9/site-packages/pandas/io/sql.py:761
../../../../../../.pyenv/versions/myenv-metabase-questions/lib/python3.9/site-packages/pandas/io/sql.py:761
../../../../../../.pyenv/versions/myenv-metabase-questions/lib/python3.9/site-packages/pandas/io/sql.py:761
../../../../../../.pyenv/versions/myenv-metabase-questions/lib/python3.9/site-packages/pandas/io/sql.py:761
../../../../../../.pyenv/versions/myenv-metabase-questions/lib/python3.9/site-packages/pandas/io/sql.py:761
  /Users/nicolasbancel/.pyenv/versions/myenv-metabase-questions/lib/python3.9/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
    warnings.warn(

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
FAILED tests/test_exercice_1_2.py::test_correct_metric_calculation - Assertio...
=================== 1 failed, 8 passed, 5 warnings in 0.66s ====================
