============================= test session starts ==============================
platform linux -- Python 3.8.14, pytest-7.4.2, pluggy-1.3.0 -- /home/janine.windhoff/code/janinewin/data-engineering-challenges/01-Software-Engineering-Best-Practices/04-Data-Lakes/03-Great-expectations/.venv/bin/python
cachedir: .pytest_cache
rootdir: /home/janine.windhoff/code/janinewin/data-engineering-challenges/01-Software-Engineering-Best-Practices/04-Data-Lakes/03-Great-expectations
configfile: pyproject.toml
plugins: anyio-4.0.0, requests-mock-1.11.0
collecting ... collected 2 items

tests/test_expectations.py::TestScraperExpectations::test_execution_of_expectations_all_passed FAILED [ 50%]
tests/test_expectations.py::TestScraperExpectations::test_execution_of_expectations_some_failed PASSED [100%]

=================================== FAILURES ===================================
______ TestScraperExpectations.test_execution_of_expectations_all_passed _______

self = <tests.test_expectations.TestScraperExpectations testMethod=test_execution_of_expectations_all_passed>
mock_send_message = <MagicMock name='send_message' id='140537812980064'>

    @patch("scraper.expectations.send_message")
    def test_execution_of_expectations_all_passed(self, mock_send_message):
        run_expectations(self.valid_df)
>       mock_send_message.assert_called_once_with("All expectations passed!")

tests/test_expectations.py:38: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <MagicMock name='send_message' id='140537812980064'>
args = ('All expectations passed!',), kwargs = {}
msg = "Expected 'send_message' to be called once. Called 2 times.\nCalls: [call('Expectation failed!'), call('site')]."

    def assert_called_once_with(self, /, *args, **kwargs):
        """assert that the mock was called exactly once and that that call was
        with the specified arguments."""
        if not self.call_count == 1:
            msg = ("Expected '%s' to be called once. Called %s times.%s"
                   % (self._mock_name or 'mock',
                      self.call_count,
                      self._calls_repr()))
>           raise AssertionError(msg)
E           AssertionError: Expected 'send_message' to be called once. Called 2 times.
E           Calls: [call('Expectation failed!'), call('site')].

../../../../../../.pyenv/versions/3.8.14/lib/python3.8/unittest/mock.py:924: AssertionError
----------------------------- Captured stderr call -----------------------------
Calculating Metrics:   0%|          | 0/85 [00:00<?, ?it/s]Calculating Metrics:   0%|          | 0/85 [00:00<?, ?it/s]Calculating Metrics:   2%|▏         | 2/85 [00:00<00:00, 1889.75it/s]Calculating Metrics:   2%|▏         | 2/85 [00:00<00:03, 21.73it/s]  Calculating Metrics:   4%|▎         | 3/85 [00:00<00:02, 32.42it/s]Calculating Metrics:   4%|▎         | 3/85 [00:00<00:04, 16.70it/s]Calculating Metrics:   4%|▎         | 3/85 [00:00<00:04, 16.70it/s]Calculating Metrics:   4%|▎         | 3/85 [00:00<00:04, 16.70it/s]Calculating Metrics:   4%|▎         | 3/85 [00:00<00:04, 16.70it/s]Calculating Metrics:   4%|▎         | 3/85 [00:00<00:04, 16.70it/s]Calculating Metrics:   4%|▎         | 3/85 [00:00<00:04, 16.70it/s]Calculating Metrics:   4%|▎         | 3/85 [00:00<00:04, 16.70it/s]Calculating Metrics:   4%|▎         | 3/85 [00:00<00:04, 16.70it/s]Calculating Metrics:  22%|██▏       | 19/85 [00:00<00:02, 23.89it/s]Calculating Metrics:  22%|██▏       | 19/85 [00:00<00:02, 23.89it/s]Calculating Metrics:  22%|██▏       | 19/85 [00:00<00:02, 23.89it/s]Calculating Metrics:  84%|████████▎ | 71/85 [00:00<00:00, 97.47it/s]Calculating Metrics:  84%|████████▎ | 71/85 [00:00<00:00, 97.47it/s]Calculating Metrics:  84%|████████▎ | 71/85 [00:00<00:00, 97.47it/s]Calculating Metrics:  88%|████████▊ | 75/85 [00:00<00:00, 97.47it/s]Calculating Metrics:  88%|████████▊ | 75/85 [00:01<00:00, 97.47it/s]Calculating Metrics:  88%|████████▊ | 75/85 [00:01<00:00, 97.47it/s]Calculating Metrics:  88%|████████▊ | 75/85 [00:01<00:00, 72.86it/s]
=========================== short test summary info ============================
FAILED tests/test_expectations.py::TestScraperExpectations::test_execution_of_expectations_all_passed
========================= 1 failed, 1 passed in 17.86s =========================
